services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: liftpad-image
        container_name: liftpad-app
        volumes:
            - ./:/var/www
            - liftpad-composer-cache:/var/cache/composer
        depends_on:
            - db
        environment:
            - DB_HOST=liftpad-db
            - DB_DATABASE=liftpad
            - DB_USERNAME=root
            - DB_PASSWORD=root
        networks:
            - liftpad-network

    db:
        image: mysql:8.0
        container_name: liftpad-db
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=liftpad
        ports:
            -   3308:3306
        volumes:
            - liftpad-db-data:/var/lib/mysql
        networks:
            - liftpad-network

    nginx:
        image: nginx:alpine
        container_name: liftpad-webserver
        ports:
            - "8081:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www
        depends_on:
            - app
        networks:
            - liftpad-network
networks:
    liftpad-network:

volumes:
    liftpad-db-data:
    liftpad-composer-cache:
